services:

  postgres:
    container_name: postgres-sql
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=rafael
      - POSTGRES_PASSWORD=1qazzaq!
      - POSTGRES_DB=bookstore
    volumes:
      - db_pg_date:/data/postgresql

volumes:
  db_pg_date: